from __future__ import annotations

ARCHETYPES = {
    "ice_crash_shadow": {
        "base_file": "build.json",
        "base_class": "Shadow",
        "default_ascendancy": "None",
        "default_main_skill": "Ice Crash",
        "default_main_skill_group": 4,
        "default_movement_skills": ["Leap Slam", "Frostblink"],
        "default_movement_group": 5,
        "stages": {
            "leveling": {
                "level": 32,
                "tree_title": "Ice Crash Shadow Leveling",
                "aura_package": "determination",
                "remove_gems": [],
                "add_gems": [],
                "config_overrides": {"enemyLevel": 32},
                "notes": "Leveling setup focused on early campaign smoothness.",
            },
            "early_maps": {
                "level": 68,
                "tree_title": "Ice Crash Shadow Early Maps",
                "aura_package": "determination_grace",
                "remove_gems": ["Contagion"],
                "add_gems": [{"group": 3, "name": "Ancestral Protector"}],
                "config_overrides": {"enemyLevel": 68},
                "notes": "Early mapping setup with more defense and a better utility package.",
            },
            "endgame": {
                "level": 90,
                "tree_title": "Ice Crash Shadow Endgame",
                "aura_package": "tanky",
                "remove_gems": ["Contagion"],
                "add_gems": [
                    {"group": 3, "name": "Ancestral Protector"},
                    {"group": 5, "name": "Molten Shell"},
                ],
                "config_overrides": {"enemyLevel": 84},
                "notes": "Endgame-oriented defensive setup with stronger utility.",
            },
        },
    },
    "boneshatter_slayer": {
        "base_file": "boneshatter_slayer_base.json",
        "base_class": "Duelist",
        "default_ascendancy": "Slayer",
        "default_main_skill": "Boneshatter",
        "default_main_skill_group": 4,
        "default_movement_skills": ["Leap Slam"],
        "default_movement_group": 5,
        "stages": {
            "leveling": {
                "level": 28,
                "tree_title": "Boneshatter Slayer Leveling",
                "aura_package": "determination",
                "remove_gems": ["Contagion", "Frostblink", "Hatred", "Herald of Ice", "Clarity"],
                "add_gems": [
                    {"group": 1, "name": "War Banner"},
                    {"group": 2, "name": "Blood and Sand"},
                    {"group": 3, "name": "Ancestral Protector"},
                    {"group": 5, "name": "Molten Shell"},
                ],
                "config_overrides": {"enemyLevel": 28},
                "notes": "Leveling Boneshatter Slayer setup focused on early campaign progression.",
            },
            "early_maps": {
                "level": 68,
                "tree_title": "Boneshatter Slayer Early Maps",
                "aura_package": "determination_grace",
                "remove_gems": ["Contagion", "Frostblink", "Hatred", "Herald of Ice", "Clarity"],
                "add_gems": [
                    {"group": 1, "name": "Pride"},
                    {"group": 2, "name": "Blood and Sand"},
                    {"group": 3, "name": "Ancestral Protector"},
                    {"group": 3, "name": "Vulnerability"},
                    {"group": 5, "name": "Molten Shell"},
                ],
                "config_overrides": {"enemyLevel": 68},
                "notes": "Early maps Boneshatter Slayer setup with stronger reservation and utility.",
            },
            "endgame": {
                "level": 90,
                "tree_title": "Boneshatter Slayer Endgame",
                "aura_package": "tanky",
                "remove_gems": ["Contagion", "Frostblink", "Hatred", "Herald of Ice", "Clarity"],
                "add_gems": [
                    {"group": 1, "name": "Pride"},
                    {"group": 2, "name": "Blood and Sand"},
                    {"group": 2, "name": "Defiance Banner"},
                    {"group": 3, "name": "Ancestral Protector"},
                    {"group": 3, "name": "Vulnerability"},
                    {"group": 5, "name": "Molten Shell"},
                    {"group": 5, "name": "Enduring Cry"},
                ],
                "config_overrides": {"enemyLevel": 84},
                "notes": "Endgame Boneshatter Slayer setup built for tougher content and stronger defense.",
            },
        },
    },
    "lightning_arrow_deadeye": {
        "base_file": "lightning_arrow_deadeye_base.json",
        "base_class": "Ranger",
        "default_ascendancy": "Deadeye",
        "default_main_skill": "Lightning Arrow",
        "default_main_skill_group": 8,
        "default_movement_skills": ["Blink Arrow", "Frostblink"],
        "default_movement_group": 5,
        "stages": {
            "leveling": {
                "level": 75,
                "tree_title": "Entering maps",
                "preferred_group_gem": "Lightning Arrow",
                "remove_alternate_groups_with_gems": ["Elemental Hit of the Spectrum"],
                "main_skill_override": "Lightning Arrow",
                "main_skill_group": 8,
                "movement_skills": ["Blink Arrow", "Frostblink"],
                "movement_group": 5,
                "aura_package": None,
                "remove_gems": [],
                "add_gems": [],
                "config_overrides": {
                    "enemyLevel": 68,
                    "bandit": "Alira",
                },
                "notes": "Lightning Arrow Deadeye leveling / entering maps setup using the Lightning Arrow group instead of the Elemental Hit fallback group.",
            },
            "early_maps": {
                "level": 85,
                "tree_title": "Starter",
                "preferred_group_gem": "Lightning Arrow",
                "remove_alternate_groups_with_gems": ["Elemental Hit of the Spectrum"],
                "main_skill_override": "Lightning Arrow",
                "main_skill_group": 8,
                "movement_skills": ["Blink Arrow", "Frostblink"],
                "movement_group": 5,
                "aura_package": None,
                "remove_gems": [],
                "add_gems": [],
                "config_overrides": {
                    "enemyLevel": 83,
                    "bandit": "Alira",
                },
                "notes": "Lightning Arrow Deadeye starter / early maps setup with the Starter tree and Lightning Arrow primary group selected.",
            },
            "endgame": {
                "level": 95,
                "tree_title": "Endgame no HH",
                "preferred_group_gem": "Lightning Arrow",
                "remove_alternate_groups_with_gems": ["Elemental Hit of the Spectrum"],
                "main_skill_override": "Lightning Arrow",
                "main_skill_group": 8,
                "movement_skills": ["Blink Arrow", "Frostblink"],
                "movement_group": 5,
                "aura_package": None,
                "remove_gems": [],
                "add_gems": [],
                "config_overrides": {
                    "enemyLevel": 84,
                    "bandit": "Alira",
                    "enemyIsBoss": "Boss",
                    "useFrenzyCharges": True,
                    "usePowerCharges": True,
                    "buffTailwind": True,
                },
                "notes": "Lightning Arrow Deadeye endgame setup using the Endgame no HH tree and Lightning Arrow primary skill group.",
            },
        },
    },
    "elementalist_kinetic_blast": {
        "base_file": "Elementalist_Kinetic_Blast_base.json",
        "base_class": "Witch",
        "default_ascendancy": "Elementalist",
        "default_main_skill": "Kinetic Blast",
        "default_main_skill_group": 1,
        "default_movement_skills": ["Shield Charge", "Faster Attacks", "Frostblink"],
        "default_movement_group": 3,
        "stages": {
            "leveling": {
                "level": 80,
                "tree_title": "update",
                "preferred_group_gem": "Kinetic Blast",
                "main_skill_override": "Kinetic Blast",
                "main_skill_group": 1,
                "movement_skills": ["Shield Charge", "Faster Attacks", "Frostblink"],
                "movement_group": 3,
                "aura_package": None,
                "remove_gems": [],
                "add_gems": [],
                "config_overrides": {
                    "enemyLevel": 68,
                    "conditionEnemyChilled": True,
                    "conditionEnemyIgnited": True,
                    "conditionEnemyShocked": True,
                },
                "notes": "Kinetic Blast Elementalist leveling / early transition setup using the existing update tree and core KB mapping package.",
            },
            "early_maps": {
                "level": 92,
                "tree_title": "update",
                "preferred_group_gem": "Kinetic Blast",
                "main_skill_override": "Kinetic Blast",
                "main_skill_group": 1,
                "movement_skills": ["Shield Charge", "Faster Attacks", "Frostblink"],
                "movement_group": 3,
                "aura_package": None,
                "remove_gems": [],
                "add_gems": [],
                "config_overrides": {
                    "enemyLevel": 83,
                    "conditionEnemyChilled": True,
                    "conditionEnemyIgnited": True,
                    "conditionEnemyShocked": True,
                    "usePowerCharges": True,
                    "useFrenzyCharges": True,
                },
                "notes": "Kinetic Blast Elementalist early maps setup focused on fast elemental clear and smooth wand mapping.",
            },
            "endgame": {
                "level": 100,
                "tree_title": "update",
                "preferred_group_gem": "Kinetic Blast",
                "main_skill_override": "Kinetic Blast",
                "main_skill_group": 1,
                "movement_skills": ["Shield Charge", "Faster Attacks", "Frostblink"],
                "movement_group": 3,
                "aura_package": None,
                "remove_gems": [],
                "add_gems": [],
                "config_overrides": {
                    "enemyLevel": 84,
                    "conditionEnemyChilled": True,
                    "conditionEnemyIgnited": True,
                    "conditionEnemyShocked": True,
                    "conditionShockEffect": 50,
                    "usePowerCharges": True,
                    "useFrenzyCharges": True,
                    "useEnduranceCharges": True,
                },
                "notes": "Kinetic Blast Elementalist endgame mapper setup using the full update tree and existing late-game elemental configuration.",
            },
        },
    },
    "spectre_summoner_necromancer": {
        "base_file": "Spectre_Summoner_Necromancer.json",
        "base_class": "Witch",
        "default_ascendancy": "Necromancer",
        "default_main_skill": "Raise Spectre",
        "default_main_skill_group": 2,
        "default_movement_skills": ["Shield Charge", "Faster Attacks", "Frostblink"],
        "default_movement_group": 6,
        "stages": {
            "leveling": {
                "level": 90,
                "tree_title": "^2Low Budget End-Game",
                "preferred_group_gem": "Raise Spectre",
                "main_skill_override": "Raise Spectre",
                "main_skill_group": 2,
                "movement_skills": ["Shield Charge", "Faster Attacks", "Frostblink"],
                "movement_group": 6,
                "aura_package": None,
                "remove_gems": [],
                "add_gems": [],
                "config_overrides": {
                    "enemyLevel": 68,
                    "feedingFrenzyFeedingFrenzyActive": True,
                    "conditionUsingFlask": True,
                    "buffOnslaught": True,
                    "minionBuffOnslaught": True,
                },
                "notes": "Spectre Summoner Necromancer leveling / low-budget transition setup using the low budget end-game tree and spectre core links.",
            },
            "early_maps": {
                "level": 95,
                "tree_title": "^2Low Budget End-Game",
                "preferred_group_gem": "Raise Spectre",
                "main_skill_override": "Raise Spectre",
                "main_skill_group": 2,
                "movement_skills": ["Shield Charge", "Faster Attacks", "Frostblink"],
                "movement_group": 6,
                "aura_package": None,
                "remove_gems": [],
                "add_gems": [],
                "config_overrides": {
                    "enemyLevel": 83,
                    "feedingFrenzyFeedingFrenzyActive": True,
                    "conditionUsingFlask": True,
                    "buffOnslaught": True,
                    "minionBuffOnslaught": True,
                    "useEnduranceCharges": True,
                },
                "notes": "Spectre Summoner Necromancer early maps setup focused on low-budget end-game progression with stable minion utility.",
            },
            "endgame": {
                "level": 97,
                "tree_title": "^4Medium Budget End-Game",
                "preferred_group_gem": "Raise Spectre",
                "main_skill_override": "Raise Spectre",
                "main_skill_group": 2,
                "movement_skills": ["Shield Charge", "Faster Attacks", "Frostblink"],
                "movement_group": 6,
                "aura_package": None,
                "remove_gems": [],
                "add_gems": [],
                "config_overrides": {
                    "enemyLevel": 84,
                    "feedingFrenzyFeedingFrenzyActive": True,
                    "conditionUsingFlask": True,
                    "buffOnslaught": True,
                    "minionBuffOnslaught": True,
                    "useEnduranceCharges": True,
                    "conditionEnemyShocked": True,
                    "conditionEnemyBlinded": True,
                    "conditionEnemyUnnerved": True,
                },
                "notes": "Spectre Summoner Necromancer endgame setup using the medium budget end-game tree and full spectre utility package.",
            },
        },
    },
    "kinetic_fusillade_totem": {
        "base_file": "Kinetic_Fusillade_Totem.json",
        "base_class": "Scion",
        "default_ascendancy": "Ascendant",
        "default_main_skill": "Kinetic Fusillade",
        "default_main_skill_group": 1,
        "default_movement_skills": ["Shield Charge", "Faster Attacks", "Frostblink"],
        "default_movement_group": 4,
        "stages": {
            "leveling": {
                "level": 68,
                "tree_title": "^xFFFADCLv 68 (3rd Lab + White Map)",
                "preferred_group_gem": "Kinetic Fusillade",
                "main_skill_override": "Kinetic Fusillade",
                "main_skill_group": 1,
                "movement_skills": ["Shield Charge", "Faster Attacks", "Frostblink"],
                "movement_group": 4,
                "aura_package": None,
                "remove_gems": [],
                "add_gems": [],
                "config_overrides": {
                    "enemyLevel": 68,
                    "conditionEnemyLightningExposure": True,
                    "conditionEnemyShocked": True,
                    "conditionShockEffect": 10,
                },
                "notes": "Kinetic Fusillade Ballista Totem leveling / early maps setup using the white map tree and core totem package.",
            },
            "early_maps": {
                "level": 85,
                "tree_title": "^xE9B3FBLv 85 (Crit Swap)",
                "preferred_group_gem": "Kinetic Fusillade",
                "main_skill_override": "Kinetic Fusillade",
                "main_skill_group": 1,
                "movement_skills": ["Shield Charge", "Faster Attacks", "Frostblink"],
                "movement_group": 4,
                "aura_package": None,
                "remove_gems": [],
                "add_gems": [],
                "config_overrides": {
                    "enemyLevel": 83,
                    "conditionEnemyLightningExposure": True,
                    "conditionEnemyShocked": True,
                    "conditionShockEffect": 10,
                    "usePowerCharges": True,
                    "useFrenzyCharges": True,
                },
                "notes": "Kinetic Fusillade Ballista Totem early maps setup using the crit swap tree and stable ranged totem mapping package.",
            },
            "endgame": {
                "level": 92,
                "tree_title": "^xE9B3FBLv 92 (Current)",
                "preferred_group_gem": "Kinetic Fusillade",
                "main_skill_override": "Kinetic Fusillade",
                "main_skill_group": 1,
                "movement_skills": ["Shield Charge", "Faster Attacks", "Frostblink"],
                "movement_group": 4,
                "aura_package": None,
                "remove_gems": [],
                "add_gems": [],
                "config_overrides": {
                    "enemyLevel": 84,
                    "conditionEnemyLightningExposure": True,
                    "conditionEnemyShocked": True,
                    "conditionShockEffect": 10,
                    "usePowerCharges": True,
                    "useFrenzyCharges": True,
                    "conditionEnemyBlinded": True,
                    "conditionEnemyBleeding": True,
                },
                "notes": "Kinetic Fusillade Ballista Totem endgame setup using the current progression tree and safe ranged totem bossing package.",
            },
        },
    },
}


def list_archetypes() -> list[str]:
    return sorted(ARCHETYPES.keys())


def get_archetype(name: str) -> dict:
    if name not in ARCHETYPES:
        raise ValueError(f"Unknown archetype: {name}")
    return ARCHETYPES[name]